class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start'
        self.MirrorCommand = 'mirror4'
        self.UnzipMirrorCommand = 'unzipmirror4'
        self.TarMirrorCommand = 'tarmirror4'
        self.CancelMirror = 'cancel4'
        self.CancelAllCommand = 'cancelall4'
        self.ListCommand = 'list4'
        self.StatusCommand = 'status'
        self.AuthorizedUsersCommand = 'users'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping'
        self.RestartCommand = 'restart4'
        self.StatsCommand = 'stats4'
        self.HelpCommand = 'help'
        self.LogCommand = 'log'
        self.SpeedCommand = 'speedtest4'
        self.CloneCommand = 'clone4'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch4'
        self.TarWatchCommand = 'tarwatch4'
        self.DeleteCommand = 'del4'
        self.UsageCommand = 'usage'
        self.MediaInfoCommand = 'mediainfo'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update'

BotCommands = _BotCommands()
