class _BotCommands:
    def __init__(self):
        self.StartCommand = 'start3'
        self.MirrorCommand = 'mirror3'
        self.UnzipMirrorCommand = 'unzipmirror3'
        self.TarMirrorCommand = 'tarmirror3'
        self.CancelMirror = 'cancel3'
        self.CancelAllCommand = 'cancelall3'
        self.ListCommand = 'list3'
        self.StatusCommand = 'sttus3'
        self.AuthorizedUsersCommand = 'users3'
        self.AuthorizeCommand = 'authorize'
        self.UnAuthorizeCommand = 'unauthorize'
        self.AddSudoCommand = 'addsudo'
        self.RmSudoCommand = 'rmsudo'
        self.PingCommand = 'ping3'
        self.RestartCommand = 'restart3'
        self.StatsCommand = 'stats3'
        self.HelpCommand = 'help3'
        self.LogCommand = 'log3'
        self.SpeedCommand = 'speedtest3'
        self.CloneCommand = 'clone3'
        self.CountCommand = 'count'
        self.WatchCommand = 'watch3'
        self.TarWatchCommand = 'tarwatch3'
        self.DeleteCommand = 'del3'
        self.UsageCommand = 'usage3'
        self.MediaInfoCommand = 'mediainfo4'
        self.ConfigMenuCommand = 'config'
        self.ShellCommand = 'shell'
        self.UpdateCommand = 'update3'

BotCommands = _BotCommands()
